// AUTO-GENERATED redirect data (old WordPress URLs -> new). Edit _build source, not here.
export const pageRedirects = [
  [
    "/about",
    "/about-us"
  ],
  [
    "/aviation-courses",
    "/aviation-courses-in-kerala"
  ],
  [
    "/courses",
    "/aviation-courses-in-kerala"
  ],
  [
    "/bba-airline-airport-management",
    "/bba-aviation"
  ],
  [
    "/blogs-articles-aviation-hospitality",
    "/articles-and-news"
  ],
  [
    "/blog",
    "/articles-and-news"
  ],
  [
    "/skywings-aviation-college-kochi-campus",
    "/kochi-campus"
  ],
  [
    "/skywings-aviation-college-mahe",
    "/mahe-campus"
  ],
  [
    "/aviation-courses-in-kerala-2",
    "/aviation-courses-in-kerala"
  ],
  [
    "/enquire-now",
    "/contact"
  ],
  [
    "/home-copy",
    "/"
  ],
  [
    "/uncategorized",
    "/articles-and-news"
  ],
  [
    "/design-branding",
    "/articles-and-news"
  ],
  [
    "/business",
    "/articles-and-news"
  ]
];

export const wildcardRedirects = [
  [
    "/tag/:s*",
    "/articles-and-news"
  ],
  [
    "/category/:s*",
    "/articles-and-news"
  ],
  [
    "/type/:s*",
    "/articles-and-news"
  ],
  [
    "/author/:s*",
    "/articles-and-news"
  ],
  [
    "/elementor-hf/:s*",
    "/"
  ],
  [
    "/wp-content/:s*",
    "/"
  ],
  [
    "/wp-admin/:s*",
    "/"
  ],
  [
    "/wp-json/:s*",
    "/articles-and-news"
  ]
];

export const imageRedirects = [
  [
    "/wp-content/uploads/2019/02/Untitled-1-1-e1740541043642.png",
    "/assets/images/skywings-aviation-academy-logo.png"
  ],
  [
    "/wp-content/uploads/2026/03/bba-aviation-colleges-in-kerala-4.webp",
    "/assets/images/bba-aviation-colleges-in-kerala-4.webp"
  ],
  [
    "/wp-content/uploads/2026/03/best-aviation-college-in-kerala-3.webp",
    "/assets/images/best-aviation-college-in-kerala-3.webp"
  ],
  [
    "/wp-content/uploads/2026/03/no.1-premium-aviation-college-in-kerala-skywings-aviation-5.webp",
    "/assets/images/no1-premium-aviation-college-kerala-5.webp"
  ],
  [
    "/wp-content/uploads/2026/03/no.1-premium-aviation-college-in-kerala-skywings-aviation-1.webp",
    "/assets/images/no1-premium-aviation-college-kerala-1.webp"
  ],
  [
    "/wp-content/uploads/2025/04/2024-07-30.jpg",
    "/assets/images/skywings-skyfest-2024.jpg"
  ],
  [
    "/wp-content/uploads/2026/03/bba-aviation-colleges-in-kerala-8.webp",
    "/assets/images/bba-aviation-colleges-in-kerala-8.webp"
  ],
  [
    "/wp-content/uploads/2026/03/training-1.svg",
    "/assets/images/expert-trainers-icon.svg"
  ],
  [
    "/wp-content/uploads/2026/03/university-1.svg",
    "/assets/images/best-aviation-college-icon.svg"
  ],
  [
    "/wp-content/uploads/2026/03/placement-1.svg",
    "/assets/images/placement-assistance-icon.svg"
  ],
  [
    "/wp-content/uploads/2026/03/homework.svg",
    "/assets/images/modern-campus-icon.svg"
  ],
  [
    "/wp-content/uploads/2026/02/06-copy.webp",
    "/assets/images/skywings-aviation-college-campus-kochi.webp"
  ],
  [
    "/wp-content/uploads/2025/04/PAI07836-min.png",
    "/assets/images/skywings-placed-students-airlines.png"
  ],
  [
    "/wp-content/uploads/2025/05/1.jpg.webp",
    "/assets/images/skywings-placed-student-01.webp"
  ],
  [
    "/wp-content/uploads/2025/05/9.jpg.webp",
    "/assets/images/skywings-placed-student-09.webp"
  ],
  [
    "/wp-content/uploads/2025/05/2.jpg.webp",
    "/assets/images/skywings-placed-student-02.webp"
  ],
  [
    "/wp-content/uploads/2025/05/3.jpg.webp",
    "/assets/images/skywings-placed-student-03.webp"
  ],
  [
    "/wp-content/uploads/2025/05/5.jpg.webp",
    "/assets/images/skywings-placed-student-05.webp"
  ],
  [
    "/wp-content/uploads/2025/05/7.jpg.webp",
    "/assets/images/skywings-placed-student-07.webp"
  ],
  [
    "/wp-content/uploads/2025/05/8.jpg.webp",
    "/assets/images/skywings-placed-student-08.webp"
  ],
  [
    "/wp-content/uploads/2025/05/12.jpg.webp",
    "/assets/images/skywings-placed-student-12.webp"
  ],
  [
    "/wp-content/uploads/2025/05/10.jpg.webp",
    "/assets/images/skywings-placed-student-10.webp"
  ],
  [
    "/wp-content/uploads/2025/05/11.jpg.webp",
    "/assets/images/skywings-placed-student-11.webp"
  ],
  [
    "/wp-content/uploads/2025/05/4.jpg.webp",
    "/assets/images/skywings-placed-student-04.webp"
  ],
  [
    "/wp-content/uploads/2025/05/6.jpg.webp",
    "/assets/images/skywings-placed-student-06.webp"
  ],
  [
    "/wp-content/uploads/2025/04/PAI08074-min-1443x1536.png",
    "/assets/images/cabin-crew-training-students-kerala.png"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_fed55c07ed78468eb832cce4446ace80_mv2.webp",
    "/assets/images/airline-recruitment-partner-8.webp"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_09b32ab65fb84033a9612026a98f3e0c_mv2.webp",
    "/assets/images/airline-recruitment-partner-2.webp"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_9866cde8af9f423e998626b77107d907_mv2.webp",
    "/assets/images/airline-recruitment-partner-5.webp"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_924c641370e244b1b1d43f5c2ee67a7b_mv2.webp",
    "/assets/images/airline-recruitment-partner-4.webp"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_1461ab3ab8394b7dbc0b026c83391726_mv2.webp",
    "/assets/images/airline-recruitment-partner-3.webp"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_e7d4e06cad84411fb32293692310cebc_mv2.webp",
    "/assets/images/airline-recruitment-partner-6.webp"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_08dc6a84744b4e0f8dd0387368808ebc_mv2.webp",
    "/assets/images/airline-recruitment-partner-1.webp"
  ],
  [
    "/wp-content/uploads/2022/05/827da0_ef384940151b4986861af9979680f619_mv2.webp",
    "/assets/images/airline-recruitment-partner-7.webp"
  ],
  [
    "/wp-content/uploads/2026/03/bba-aviation-colleges-in-kerala-1.webp",
    "/assets/images/bba-aviation-colleges-in-kerala-1.webp"
  ],
  [
    "/wp-content/uploads/2022/07/PAI01337.jpg",
    "/assets/images/skywings-smart-classroom-kochi.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/PAI07914-min.png",
    "/assets/images/skywings-academy-students-kochi.png"
  ],
  [
    "/wp-content/uploads/2026/01/freepik__design-editorial-soft-studio-light-photography-hig__41438.png",
    "/assets/images/professional-presentation-training-skywings.webp"
  ],
  [
    "/wp-content/uploads/2022/07/PAI01272.jpg",
    "/assets/images/aviation-management-training-kochi.jpg"
  ],
  [
    "/wp-content/uploads/2022/07/PAI01209.jpg",
    "/assets/images/cabin-crew-practical-training-skywings.jpg"
  ],
  [
    "/wp-content/uploads/2022/07/PAI00978.jpg",
    "/assets/images/logistics-training-skywings-academy.jpg"
  ],
  [
    "/wp-content/uploads/2022/07/PAI00910-acopy-Copy.jpg",
    "/assets/images/aviation-hospitality-training-skywings.jpg"
  ],
  [
    "/wp-content/uploads/2022/07/PAI01543.jpg",
    "/assets/images/skywings-academy-campus-kochi.jpg"
  ],
  [
    "/wp-content/uploads/2026/02/02.png",
    "/assets/images/aviation-student-skywings-kochi.png"
  ],
  [
    "/wp-content/uploads/2025/04/ADA05317.jpg",
    "/assets/images/global-aviation-career-scope-skywings.jpg"
  ],
  [
    "/wp-content/uploads/2026/02/01.png",
    "/assets/images/cabin-crew-student-skywings-kochi.png"
  ],
  [
    "/wp-content/uploads/2026/02/05.png",
    "/assets/images/airline-airport-management-student-skywings.png"
  ],
  [
    "/wp-content/uploads/2022/07/PAI00924.jpg",
    "/assets/images/airport-terminal-operations-training.jpg"
  ],
  [
    "/wp-content/uploads/2026/02/04.png",
    "/assets/images/bba-logistics-student-skywings.png"
  ],
  [
    "/wp-content/uploads/2026/01/02.png",
    "/assets/images/bba-logistics-career-scope.webp"
  ],
  [
    "/wp-content/uploads/2025/04/ADA05353.jpg",
    "/assets/images/premium-logistics-training-skywings.jpg"
  ],
  [
    "/wp-content/uploads/2026/02/06.png",
    "/assets/images/aviation-hospitality-student-skywings.png"
  ],
  [
    "/wp-content/uploads/2025/04/fg.jpg",
    "/assets/images/skywings-annual-event-kerala.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/ff.jpg",
    "/assets/images/skywings-convocation-ceremony.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/AJI00248.jpg",
    "/assets/images/skywings-aviation-students-event.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/AJI00156.jpg",
    "/assets/images/skywings-award-ceremony-kerala.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/2022-04-10.jpg",
    "/assets/images/skywings-inauguration-2022.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/unnbnamed.jpg",
    "/assets/images/skywings-premium-campus-kochi.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/gg.jpg",
    "/assets/images/skywings-aviation-college-students.jpg"
  ],
  [
    "/wp-content/uploads/2025/04/pngwing.com_.png",
    "/assets/images/admissions-open-2026-badge.png"
  ],
  [
    "/wp-content/uploads/2025/04/100placementpng.png",
    "/assets/images/100-percent-placement-badge.png"
  ],
  [
    "/wp-content/uploads/2026/03/bba-aviation-colleges-in-kerala-3.webp",
    "/assets/images/bba-aviation-colleges-in-kerala-3.webp"
  ],
  [
    "/wp-content/uploads/2026/03/best-aviation-college-in-kerala-2.webp",
    "/assets/images/best-aviation-college-in-kerala-2.webp"
  ],
  [
    "/wp-content/uploads/2026/05/layer-3.png",
    "/assets/images/cabin-crew-recruitment-skywings-kochi.png"
  ],
  [
    "/wp-content/uploads/2022/07/PAI01209-768x512.jpg",
    "/assets/images/airport-management-course-kerala-students.jpg"
  ],
  [
    "/wp-content/uploads/2026/03/no.1-premium-aviation-college-in-kerala-skywings-aviation-5-300x200.webp",
    "/assets/images/no1-premium-aviation-college-kerala-5-300x200.webp"
  ],
  [
    "/wp-content/uploads/2026/03/bba-aviation-colleges-in-kerala-4-300x200.webp",
    "/assets/images/bba-aviation-colleges-in-kerala-4-300x200.webp"
  ],
  [
    "/wp-content/uploads/2026/03/best-aviation-college-in-kerala-3-300x200.webp",
    "/assets/images/best-aviation-college-in-kerala-3-300x200.webp"
  ],
  [
    "/wp-content/uploads/2026/03/no.1-premium-aviation-college-in-kerala-skywings-aviation-1-300x200.webp",
    "/assets/images/no1-premium-aviation-college-kerala-1-300x200.webp"
  ]
];
